### PR TITLE
Fixing dependency

### LINKED ISSUE #2: package.json dependencies break
Hi,

Would like to know why the unicode-7.0.0 package is not locked at any version:
"unicode-7.0.0": "x"

In this few days we tried deploy one of our app again but it crashes. We suspect this was caused by a new release of unicode-7.0.0.

```
TypeError: Cannot read property 'forEach' of undefined
langdetect/index.js:249:
        unicode.blocks.forEach(function (unicode_block) {
                UnicodeBlocks.push({
                        name: unicode_block,
                        regex: require('unicode-7.0.0/blocks/' + unicode_block + '/regex')
                });
        });
```

Is it possible to fix it by a new release of langdetect which locks to a specific version of unicode-7.0.0? Your help will be much appreciated!

Simon

### PR DESCRIPTION
**Pull request by DavidBruant**
It used to work with 0.1.5. This should be a quick way to fix #2

### CODE REVIEW

**Comment by DavidBruant** [comment]
[It appears](https://github.com/newmsz/node-language-detection/issues/2#issuecomment-230465882) 0.5.0 might work too. But changing from `blocks` to `Block` might be a more appropriate fix.

**Comment by mathiasbynens** [comment]
Yes, please update to a more recent version, use `Block` instead of `blocks`, and update to `unicode-9.0.0` while we’re at it :)

**Comment by mathiasbynens** [comment]
I’ve updated my old PR (#1) to do just that.

**Comment by DavidBruant** [comment]
Closing this PR since it does not add any value over #1.
Thanks @mathiasbynens :-)

**Pull request closed without merging**
